### ISSUE TITLE
Support for Qt6 is missing

### ISSUE THREAD

**Issue by ieroglyph** [songyuncen/QtJsonSettings#4]
To be seamlessly used with Qt6-based projects, basically only the CMakeLists.txt need some tweaking.
It's possible either to switch to "versionless" option of including Qt modules in the project, but in this way compatibiliity with Qt prior to 5.15 will be lost.
So, using this solution is proposed:
https://doc.qt.io/qt-6/cmake-qt5-and-qt6-compatibility.html#supporting-older-qt-5-versions

**Comment by ieroglyph** [comment]
#3 helps having universal library.

**Comment by songyuncen** [comment]
Hi
I merge your PR, thanks!
